[project]
name =  "project-name"
authors = [
    {name = "Robert Howlett"},
]
description = ""
readme = "README.md"
requires-python = ">=3.8.1"
dependencies = [
    "python-Levenshtein==0.22.0",
]
version = "0.1.0"

[dependency-groups]
dev = [
    "ruff==0.12.2",
]

[tool.ruff]
line-length = 120
